### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by MiguelRuizG** [yan9a/serial#8]
Hi, I think I found a typo in line 175 of the ceSerial.h, in the SetBaudRate function. The if is -> (baudrate = 1100)  but sets the baud at 110_CBR.

**Comment by srmeister** [comment]
here is another typo:

line 202 is missing `std::` at the beginning.
it should be
`	std::wstring wtext(port.begin(),port.end());`

**Comment by yan9a** [comment]
Fixed the issues. Thank you!
